import Header from '@/components/Header'
import Head from 'next/head'
import Feed from '@/components/Feed'
import Modal from '@/components/Modal'
import Modalstory from '@/components/Modalstory'
import  Modalchat  from '@/components/Modalchat'
import { useRouter } from 'next/router'
import Modaldispstory from '@/components/Modaldispstory'
import Image from 'next/image'
import { BrowserRouter as Router,Route,Routes } from 'react-router-dom'
export default function Home() {
  return (
    <>
      <Head>
    <title>INSTAGRAM 2.0</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/insta.png" />
  </Head>
   <div className='scrollbar-thin scrollbar-thumb-[black]'>
  {/*header*/}
  <Header/>
  {/*feed*/}
  <Feed/>
  {/*Modal*/}
  <Modal/>
  <Modalstory/>
  <Modalchat/>
    <Modaldispstory/>
</div>
</>
  )
}
